spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.devyoon.kr/realms/jungryrealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  admin-uri: https://keycloak.devyoon.kr/admin/realms/jungryrealm