server:
  port: 48080
spring:
  config:
    import:
      - classpath:/ignore/moneymoa-database.yaml
      - classpath:/ignore/moneymoa-security.yaml
  application:
    name: moneymoa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: debug