name: CI/CD for Synology

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with SSH
        uses : appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SYNOLOGY_DOMAIN }}
          username: ${{ secrets.SYNOLOGY_USER }}
          password: ${{ secrets.SYNOLOGY_PASSWORD }}
          port: ${{ secrets.SYNOLOGY_PORT }}
          script: |
            if [ ! -d "moneymoa" ]; then
              git clone ${{ secrets.CLONE_ADDR }}
            else
              cd moneymoa
              git pull origin main
            fi
            
            /usr/local/bin/docker build -t moneymoa-backend .
            
            /usr/local/bin/docker stop moneymoa-backend || true
            /usr/local/bin/docker rm moneymoa-backend || true
            
            /usr/local/bin/docker run -d --name moneymoa-backend -p 48000:48000 moneymoa-backend
            
            echo "Deploy Complete"